version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "ci"]

  - package-ecosystem: "docker"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "docker"]

  - package-ecosystem: "docker"
    directory: "/src/productcatalogservice"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "docker"]

  - package-ecosystem: "docker"
    directory: "/src/cartservice/src"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "docker"]

  - package-ecosystem: "docker"
    directory: "/src/checkoutservice"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "docker"]

  - package-ecosystem: "npm"
    directory: "/src/currencyservice"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "npm"]

  - package-ecosystem: "npm"
    directory: "/src/paymentservice"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "npm"]

  - package-ecosystem: "terraform"
    directory: "/infra/environments/aws"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "terraform"]
    ignore:
      - dependency-name: "hashicorp/aws"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "terraform"
    directory: "/infra/bootstrap/state"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "terraform"]
    ignore:
      - dependency-name: "hashicorp/aws"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "gomod"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "go"]

  - package-ecosystem: "gomod"
    directory: "/src/productcatalogservice"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "go"]

  - package-ecosystem: "gomod"
    directory: "/src/checkoutservice"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "go"]

  - package-ecosystem: "gomod"
    directory: "/src/shippingservice"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "go"]

  - package-ecosystem: "pip"
    directory: "/src/emailservice"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "python"]
